### ISSUE TITLE
Looks like not work with the latest VisRuntime now

### ISSUE THREAD

**Issue by xeoshow** [kotcrab/viseditor-superjumper-demo#1]
Hi,

Just tried this demo, but looks like not work with the latest VisRuntime now, how to run the demo or is there any other workable demo?

Thanks!

**Comment by kotcrab** [comment]
If by latest you meant VisRuntime version 0.3.0 then this should be fixed now, Gradle was using old 0.3.0-SNAPSHOT.

If you meant 0.3.1-SNAPSHOT then check [vis-031](https://github.com/kotcrab/viseditor-superjumper-demo/tree/vis-031) branch.

Thanks for reporting.
