### ISSUE TITLE
how to make button

### ISSUE THREAD

**Issue by blademaster-888** [kotcrab/viseditor-superjumper-demo#3]
HI, this isn't really an issue more like a feature that isn't there. In your example you made the sound icon on and off but is there a way I can make it like a libgdx button with button pressed/unpressed? the button feature is in overlap2d and it was easy to use but coming to this I am not sure how to implement a button. thanks.

**Comment by kotcrab** [comment]
There are more buttons in this demo that are normal buttons (not toggle button like sound mute) but they all use sprites to make it simpler. They don't change image on state down nor use listeners. If you really want to you can create something like `Button` component holding references to `ButtonListener`. Then create `ButtonSystem` which would iterate over entities having `Button` and `VisSprite` components check if it was pressed and dispatch event to `ButtonListener`. It could even update image to pressed / unpressed state. That said though I think it is better to use libgdx's [`scene2d.ui`](https://github.com/libgdx/libgdx/wiki/Scene2d.ui) to create UI and keep it separate from game level.
